(define-module (routes)
  #:use-module (srfi srfi-1)
  #:use-module (web request)
  #:use-module (web uri)
  #:use-module (git)
  #:use-module (templates server)
  #:use-module (routes home)
  #:use-module (routes explore)
  #:use-module (routes repository)
  #:use-module (routes status)
  #:export (router))

(define (get-page-sections url)
  (drop (string-split url #\/) 1))

(define (router request body)
  (let ((url (uri-path (request-uri request))))
    (cond
     ((equal? url "/")
      (respond (route-home)))
     ((equal? url "/explore")
      (respond (route-explore)))
     ((equal? (car (get-page-sections url)) "repository")
      (respond (route-repository (cadr (get-page-sections url)))))
     (else (route-not-found request)))))
